config/routes.rb
Dropshare::Application.routes.draw do
  get "drive/login"
  get "drive/upload"
  get "drive/download"
  get "drive/logout"
  root 'users#index'
  match '/signup', to: 'users#new', via: 'get'
  
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Below this line added from omniauth-facebook tutorial
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_drive
    @current_drive ||= User.find(session[:drive]) if session[:drive]
  end
  
  helper_method :current_drive
  helper_method :current_user
end

app/controllers/drive_controller.rb
class DriveController < ApplicationController
  def login(username, password)
    session[:drive] = GoogleDrive.login(username, password)
    redirect_to root_url
  end

  def upload(uploadpath, uploadfile, convertTF)
    session[:drive].upload_from_file(uploadpath, uploadfile, :convert => convertTF)
    
  end

  def download(downloadfile, path)
    @filetodownload = session[:drive].file_by_title(downloadfile)
    @filetodownload.download_to_file(path)
  end

  def logout
    session[:drive] = nil
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      user = User.from_omniauth(env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to root_url
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
    def full_title(page_title)
      base_title = "Dropshare"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/google_helper.rb
module GoogleHelper
  def login_url
    redirect_uri = ApplicationController::BASEURL + '/oauth2callback'
    url =
      'https://accounts.google.com/o/oauth2/auth?' +
        'scope='+
        ApplicationController::OAUTH_SCOPE + '&' +
        'redirect_uri='+ redirect_uri + '&' +
        'response_type=code&' + 
        'client_id=' +
        ApplicationController::CLIENT_ID + '&' + 
        'access_type=offline'

    URI.parse(URI.encode(url.strip))
  end
  def get_tokens(code)
    params['code'] = code
    params['client_id'] = ApplicationController::CLIENT_ID
    params['client_secret'] = ApplicationController::CLIENT_SECRET
    params['redirect_uri'] = ApplicationController::BASEURL + '/oauth2callback'
    params['grant_type'] = 'authorization_code'
    # Initialize HTTP library
    url = URI.parse('https://accounts.google.com')
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE #use verify_peer
    request = Net::HTTP::Post.new('/o/oauth2/token')
    request.set_form_data(params)
    response = http.request(request)
    JSON.parse(response.body)
  end
  
  def call_api(path, access_token)
    access_token.to_s
    url = URI.parse('https://www.googleapis.com')
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE #use verify_peer

    #Make request to API
    request = Net::HTTP::Get.new(path)
    request['Authorization'] = 'Bearer ' + access_token
    response = http.request(request)
    JSON.parse(response.body)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drive/download.html.haml
%h1 Drive#download
%p Find me in app/views/drive/download.html.erb

app/views/drive/login.html.haml
WORK IN PROGRESS LOL

app/views/drive/logout.html.haml
%h1 Drive#logout
%p Find me in app/views/drive/logout.html.erb

app/views/drive/upload.html.haml
%h1 Drive#upload
%p Find me in app/views/drive/upload.html.erb

app/views/layouts/_facebook_signup.html.erb
<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% if current_drive %> 
      you're facebook and drive accounts are connected
      <%= link_to "Sign out of Drive", drive_logout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "sign into Google Drive", "/auth/GoogleDrive", id: "sign_in" %>
    <% end %>
  <% else %>
    <%= link_to "Sign up with Facebook", "/auth/facebook", id: "sign_in"  %>
  <% end %>
</div>

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "#"} Dropshare
    by Max Harris | Dylan Shepard | Luke Woodruff
  %nav
    %ul
      %li= link_to "About",   '#'
      %li= link_to "Contact", '#'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Dropshare", '/', id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home",    root_path
          %li= link_to "Help",    '#'
          %li=render 'layouts/facebook_signup'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'

app/views/users/index.html.haml
.center.hero-unit
  %h1 Welcome to Dropshare
  %h2
    This is the home page for Dropshare
  %p (at least for time being)
  = render 'layouts/facebook_signup' 
/
  <haml:loud> provide(:title, &amp;#39;Home&amp;#39;)</haml:loud>
  <h1>Home</h1>
  <p>This is the home page (for the time being) for Dropshare</p>
  <a href="/signup" class="btn btn-large btn-primary">Sign up now!</a>

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
%p
  This is the sign up page for Dropshare
  = render 'layouts/facebook_signup'